- hosts: app
  tasks:
    - name: Copy Artifact
      copy:
        src: main
        dest: /home/vagrant/main
    - name: Copy Service Definition
      copy:
        src: myapp.service
        dest: /etc/systemd/system/myapp.service
      become: true
    - name: Start systemd
      systemd:
        name: myapp
        state: started 