- hosts: app
  tasks:
    - name: Stop the service
      ansible.builtin.systemd_service:
        name: myapp
        state: stopped
      become: true
      
    - name: Copy Artifact
      copy:
        src: main
        dest: /home/vagrant.linux/main

    - name: Fix executable permissions
      ansible.builtin.file:
        path: /home/vagrant.linux/main         
        mode: '0777'
        
    - name: Copy Service Definition
      copy:
        src: myapp.service
        dest: /etc/systemd/system/myapp.service
      become: true
