name: NodeJS with Grunt

on:
  push:
    branches: [ "main", "dev"]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: node --test

    - name: Build Docker image
      run: |
        docker build -t ttl.sh/myapp1 .

    - name: Push Docker image to Docker Hub
      run: docker push ttl.sh/myapp1

  deploy-staging:
    runs-on: self-hosted
    needs: build
    steps:
      - shell: bash
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          SUPER_SECRET: ${{secrets.SSH_KEY}}
        run: |
          echo "$SUPER_SECRET" > ~/.ssh/id_rsa_github
          chmod 600 ~/.ssh/id_rsa_github
          ansible-playbook --key-file ~/.ssh/id_rsa_github -i staging.ini playbook.yml
          
  deploy-production:
      runs-on: self-hosted
      needs: build
      if: github.ref == 'refs/heads/main'
      steps:
        - shell: bash
          env:
            ANSIBLE_HOST_KEY_CHECKING: 'false'
            SUPER_SECRET: ${{secrets.SSH_KEY}}
          run: |
            echo "$SUPER_SECRET" > ~/.ssh/id_rsa_github
            chmod 600 ~/.ssh/id_rsa_github
            ansible-playbook --key-file ~/.ssh/id_rsa_github -i production.ini playbook.yml

      

